# Generated by Django 2.2 on 2019-09-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
