# Generated by Django 2.2 on 2019-09-18 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
