# Generated by Django 2.2 on 2019-09-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
